### ISSUE TITLE
Having a hard time using this to build without documentation

### ISSUE THREAD

**Issue by FocuzJS** [unixpickle/gobfuscate#1]
I've tried many variations as well as reading over the code to figure out what I'm doing wrong. My project folder is in /Users/user/go/enc (which is the default GOPATH used in the source) with enc.go in the folder and i get: 
`Failed to build import graph: enc`

**Comment by unixpickle** [comment]
Without knowing more about your setup, it's hard to say. Maybe it's because you don't have a `src` directory? For instance, if your GOPATH is `/Users/user/go`, then your enc.go file should be in `/Users/user/go/src/enc/enc.go`.

**Comment by FocuzJS** [comment]
For some reason it finally worked with the `-outdir` flag and manually exporting the correct paths

**Comment by unixpickle** [comment]
What do you mean "exporting the correct paths"? I'd like to make this easier for people to use going forward, so any recommendations are welcome.
