### ISSUE TITLE
Reversing

### ISSUE THREAD

**Issue by vtolstov** [unixpickle/gobfuscate#16]
Does it possible to create reverse mapping map, so when you have binary and this map,restore original names?
For example to use with go panics

**Comment by unixpickle** [comment]
If you use a fixed encryption key (by passing `-enckey`), then the names will be encrypted in a reproducible way. This way, you could theoretically scan your existing `$GOPATH` and find names that encrypt to the names in the obfuscated binary. However, this is not built in to the current tool.

**Comment by vtolstov** [comment]
thanks!
