### ISSUE TITLE
invalid identifier "_"

### ISSUE THREAD

**Issue by CaledoniaProject** [unixpickle/gobfuscate#20]
Not sure what this means,

```
Renamed 1 occurrence in 1 file in 1 package.
Renamed 5 occurrences in 2 files in 1 package.
Failed to obfuscate symbols: top-level renaming: -from: invalid identifier "_"
```

Can you help?

**Comment by unixpickle** [comment]
Interesting. Is this on an open source repo, and/or could you try to isolate the culprit code file and post it here?

**Comment by CaledoniaProject** [comment]
`-verbose` does not add anything useful, how can I do that?

**Comment by unixpickle** [comment]
I would try a manual search process, e.g. continually reduce the size of the project you are obfuscating by deleting code and replacing it with filler, until you have a minimal reproduction.

**Comment by tggo** [comment]
if found this issue in  pkg:
[golang/sys/unix/ztypes_linux_amd64.go](https://github.com/golang/sys/blob/6254a7c3cac686fe2a53a481f189cea00afecc17/unix/ztypes_linux_amd64.go#L96)

`type _Gid_t uint32`

**Comment by CaledoniaProject** [comment]
@tggo gobfuscate does not support the `_ Type` syntax as well, if you have time to fix it :-)

```
func xxx(proto int, _ Type, b []byte) (xxx, xxx)
```
