### ISSUE TITLE
flag provided but not defined

### ISSUE THREAD

**Issue by notdodo** [unixpickle/gobfuscate#32]
Hi!

While trying the tool I simply executed:

`gobfuscate test ./`
and the output was:

```
2020/02/02 15:22:05 Copying GOPATH...
2020/02/02 15:22:13 Obfuscating package names...
2020/02/02 15:22:13 Obfuscating strings...
2020/02/02 15:22:13 Obfuscating symbols...
Renamed 4 occurrences in 1 file in 1 package.
flag provided but not defined: -ldflags "-s -w -extldflags '-static'"
usage: go build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
Failed to compile: exit status 2
exit status 1
```
I've read that the issue could be due to a regression in Golang 1.13 due to `flag.Parse()` called before the flags initialization, so I stripped, in `main.go`

```go
func main() {
	pkgName := "test"
	outPath := "./"

	if !obfuscate(pkgName, outPath) {
		os.Exit(1)
	}
}
```

But the output is the same of above.
Go version is: `go1.13.7 linux/amd64`

main.go is:

```go
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello World!")
}
```

**Comment by usualwyy** [comment]
it should be like:
`ldflags := `-ldflags="-s -w`
	if winHide {
		ldflags += " -H=windowsgui"
	}
	if !noStaticLink {
		ldflags += ` -extldflags '-static'`
	}
	ldflags += `"`
	tagsFlag := `-tags="` + tags + `"``

**Comment by danilofaria** [comment]
im having the same issue with a hello world go file
