### ISSUE TITLE
copyDep won't work correctly when GOPATH is a list of paths

### ISSUE THREAD

**Issue by XiaoMouR** [unixpickle/gobfuscate#4]
If GOPATH is a list of paths, like ```GOPATH=/a/gopath1:/b/gopath2```, the copyDep function won't get the correct package path, which makes it failed.

**Comment by unixpickle** [comment]
Should be fixed by 4fdc564a457cad4b9f45f35b3cc11aa54e173bf7. If not, let me know and I will re-open this issue.
