### ISSUE TITLE
Error happens when renaming a build-tags specific symbol

### ISSUE THREAD

**Issue by XiaoMouR** [unixpickle/gobfuscate#5]
A demo package like follows,
main.go
```
package main

func main() {
   Test()
}
```
a.go
```
// +build TagA

package main
import "fmt"
var A = "A"
func Test() {
  fmt.Println("I'm tag ", A)
}
```
b.go
```
// +build !TagA
 
package main
func Test() {
  fmt.Println("I'm not A")
}
```
When try to obfuscate this package, it will report an error  like `top-level renaming: package "xxxxx" has no member "A"`.

**Comment by leibiao** [comment]
Is there some way that we can omit the symbol refactor of **a.go**?
